name: Release JS Bundle

run-name: Release version ${{ github.ref_name }}

on:
  release:
    types: [published]

jobs:
  build-release-js-bundle:
    name: Build Release JS Bundle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn install
      - run: yarn build

      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/*